services:
  - type: web
    name: academiq-java-api
    env: docker
    branch: main
    dockerfilePath: ./Dockerfile
    instanceType: free
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
